### ISSUE TITLE
Correcciones del DER

### ISSUE THREAD

**Issue by lila-papazian** [tomasdepi/gdd-2c-2017#1]
- [x] El cliente debe registarse tanto en el factura como en el pago, porque el pago es de un cliente, y la factura de un cliente, que en enunciado solo se peremita pagar un factura de un mismo cliente es una mera casualidad, si vos queres podrías llegar a pagar las facturas de cualquier persona, porque yo registro el pago de una persona sobre una factura particular.

- [ ] Del mismo modo que plantean una entidad intermedia entre factura y rendición, pueden aplicar el mismo concepto para los pagos, dado que independientemente si hay o no devolución siempre tendría que quedar registrado como fue el pago efectuado, de manera de poder resconstruir el pago original independientemente si luego hubo devolución de una factura particular. Ademas tengan presente que se pueden pagar mas de una factura al mismo tiempo

- [ ] Ojo que las devoluciones son sobre facturas, la entidad devolución no permite determinar que factura en si de devolvió.

- [ ] La forma de pago debe ser modelada.

**Comment by lila-papazian** [comment]
Cree la estructura intermedia que piden, y cambié las relaciones que tenía Devolución para conectarlo con la Entidad Factura.
También agregué FK de la factura para devolver
Todavía no me pude sentar con el resto, pero lo saco en la semana

**Comment by tomasdepi** [comment]
Excelente. Si van a cambiar el DER, también actualicen el script de migracion para que sea acorde. Si te animas intenta cambiarlo, sino lo hago yo el finde

**Comment by lila-papazian** [comment]
Hoy que tengo un rato me pongo con eso me parece, cualquier cosa pregunto por el grupo

El oct. 12, 2017 10:36 PM, tomasdepi <notifications@github.com> escribió:

Excelente. Si van a cambiar el DER, también actualicen el script de migracion para que sea acorde. Si te animas intenta cambiarlo, sino lo hago yo el finde
